name: Daily Prime Generator

on:
  workflow_dispatch:

jobs:
  generate-primes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create swap
        uses: pierotofy/set-swap-space@v1.0
        with:
          swap-size-gb: 8

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libboost-all-dev

      - name: Build project
        run: |
          g++ -o prime_generator src/main.cpp -lboost_system

      - name: Run prime generator
        run: |
          ./prime_generator

      - name: Commit and push generated files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add *.txt
          git commit -m "Update prime numbers"
          git push

      - name: Trigger workflow
        run: |
          sleep 5
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.WORKFLOW_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/daily-prime-generator.yml/dispatches \
            -d '{"ref":"main"}'
